### ISSUE TITLE
rostopic pub functionality

### ISSUE THREAD

**Issue by huckl3b3rry87** [jdlangs/RobotOS.jl#28]
disclaimer: I am still a ROS noob, but I am starting to catch on a bit.

This is what I am trying to do through RobotOS.jl:
```
  rostopic pub -r 20 /gazebo/set_model_state gazebo_msgs/ModelState '{model_name: lidar_example, pose: { position: { x: 10, y: 0, z: 2 }, orientation: {x: 0, y: 0, z: 0, w: 0 } }, twist: { linear: { x: 0, y: 0, z: 0 }, angular: { x: 0, y: 0, z: 0}  }, reference_frame: world }'
```
But I am having some trouble since the topic has a ```model_name``` and looks like this:
```
rostopic echo /gazebo/model_states
```
and looks like this:
```
---
name: ['ground_plane', 'lidar_example']
pose: 
  - 
    position: 
      x: 0.0
      y: 0.0
      z: 0.0
    orientation: 
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  - 
    position: 
      x: 10.0
      y: 0.0
      z: 1.99706
    orientation: 
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
twist: 
  - 
    linear: 
      x: 0.0
      y: 0.0
      z: 0.0
    angular: 
      x: 0.0
      y: 0.0
      z: 0.0
  - 
    linear: 
      x: 0.0
      y: 0.0
      z: -0.2352
    angular: 
      x: 0.0
      y: 0.0
      z: 0.0
---
```
Or maybe I am doing something silly again? I am just trying to set the position of something in Gazebo. I guess thinking about this more it seems I might be doing something silly, because when I do a ``rostopic pub`` it occupies a node and then it just keeps publishing the same command, when what I need if for that command to be updated.
